### PR TITLE
611: Fix - Expand side menu workflows/project when workflow is open

### LINKED ISSUE #611: Expand side menu workflows/project when workflow the from project is opened
Expand side menu workflows/project when workflow from the project is opened.

### PR DESCRIPTION
**Pull request by jozefbakus**
Implements #611

Expand side menu workflows/project when workflow from the project is opened.

### CODE REVIEW

File: ui/src/app/components/workflows/workflows.component.ts [hunk 1]
```diff
@@ -45,6 +47,27 @@ export class WorkflowsComponent implements AfterViewInit, OnDestroy {
...
   }
 
+  isWorkflowHighlighted(id: number): boolean {
+    return this.router.url.split('/').some((part) => part === id.toString());
+  }
+
+  isProjectClosed(project: string, workflows: WorkflowIdentityModel[]): boolean {
+    const isOpen =
+      this.openedProjects.has(project) || workflows.some((workflow: WorkflowIdentityModel) => this.isWorkflowHighlighted(workflow.id));
+    if (isOpen && !this.openedProjects.has(project)) {
```
Comment (kevinwallimann) [inline ui/src/app/components/workflows/workflows.component.ts]: Little bit redundant logic. If you expand this, it reads
`(A || B) && !A`, which is equivalent to `(A && !A) || (B && !A)`, which is equivalent to `B && !A`,
where `A = this.openedProjects.has(project)`, `B = workflows.some((workflow: WorkflowIdentityModel) => this.isWorkflowHighlighted(workflow.id))`.

So I would rewrite this if-condition like this:
`if(!this.openedProjects.has(project) && workflows.some((workflow: WorkflowIdentityModel) => this.isWorkflowHighlighted(workflow.id))) {`

File: ui/src/app/components/workflows/workflows.component.ts [hunk 2]
```diff
@@ -45,6 +47,27 @@ export class WorkflowsComponent implements AfterViewInit, OnDestroy {
...
+      this.openedProjects.add(project);
+    }
+    return !isOpen;
```
Comment (kevinwallimann) [inline ui/src/app/components/workflows/workflows.component.ts]: Here, you could then just return `this.openedProjects.has(project)`

Imo, the logic is a bit easier to follow than the detour over `isOpen`

File: ui/src/app/components/workflows/workflows.component.spec.ts [hunk 3]
```diff
@@ -65,4 +72,106 @@ describe('WorkflowsComponent', () => {
...
+        const idNonMatching = 5;
+        router.navigate(['workflows/show', 555]).then(() => {
+          expect(underTest.isWorkflowHighlighted(idNonMatching)).toBeFalse();
+        });
+      }),
+    );
+  });
+
+  it(
+    'openCloseProject() should toggle a project',
```
Comment (kevinwallimann) [inline ui/src/app/components/workflows/workflows.component.spec.ts]: nitpick: `toggleProject` instead of `openCloseProject` might be a bit easier to understand

File: ui/src/app/components/workflows/workflows.component.ts (hunk 2 above)
Comment (jozefbakus) [reply ui/src/app/components/workflows/workflows.component.ts]: Should be !this.openedProjects.has(project). Fixed.

File: ui/src/app/components/workflows/workflows.component.ts (hunk 1 above)
Comment (jozefbakus) [reply ui/src/app/components/workflows/workflows.component.ts]: Nice, thanks. Fixed.

File: ui/src/app/components/workflows/workflows.component.spec.ts (hunk 3 above)
Comment (jozefbakus) [reply ui/src/app/components/workflows/workflows.component.spec.ts]: Yes, you are right. Fixed

**Review by kevinwallimann — APPROVED** [review]
