### PR TITLE
#489, #490, #494  Config fix

### LINKED ISSUE #489: Use auth inmemory config properties
Currently, the in-memory username and password are hard-coded. The values should be set by the config properties `auth.inmemory.user` and `auth.inmemory.password` or these config properties should be removed from the `application.properties`.

### LINKED ISSUE #490: Use the shellExecutor.executablesFolder property
Currently the `shellExecutor.executablesFolder` property is only used in a test. It should be used in the `ShellExecutor` and prepend paths to shell scripts. If it doesn't need to be used, the property should be removed.

### LINKED ISSUE #494: Use the sparkYarnSinkConfig.executablesFolder property
Currently the sparkYarnSinkConfig.executablesFolder property is only used in a test. It should be used in the SparkExecutor and prepend paths to files. If it doesn't need to be used, the property should be removed.

### PR DESCRIPTION
**Pull request by jozefbakus**
Implements: #489 - Use auth inmemory config properties
Implements: #490 - Use the shellExecutor.executablesFolder property
Implements: #494 - Use the sparkYarnSinkConfig.executablesFolder property

### CODE REVIEW

**Review by kevinwallimann — DISMISSED** [review]

File: src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/utils/JobTemplateResolutionUtil.scala [hunk 1]
```diff
@@ -15,13 +15,17 @@
...
+import za.co.absa.hyperdrive.trigger.configuration.application.{ShellExecutorConfig, SparkYarnSinkConfig}
 
+import java.nio.file.Paths
+import javax.inject.Inject
 import scala.util.{Failure, Success, Try}
 
-
-object JobTemplateResolutionUtil {
+@Component
+class JobTemplateResolutionUtil @Inject()(sparkYarnSinkConfig: SparkYarnSinkConfig, shellExecutorConfig: ShellExecutorConfig) {
```
Comment (kevinwallimann) [inline src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/utils/JobTemplateResolutionUtil.scala]: I think you should rename the class so it doesn't end in `Util` and also move it to some other package, since utils are supposed to be singleton objects. Otherwise, you can pass the executables folder variables.

Comment (jozefbakus) [reply src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/utils/JobTemplateResolutionUtil.scala]: Ok, I made service of it

File: src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateService.scala [hunk 2]
```diff
@@ -35,15 +34,15 @@ trait JobTemplateService {
 }
 
 @Service
-class JobTemplateServiceImpl(override val jobTemplateRepository: JobTemplateRepository) extends JobTemplateService {
+class JobTemplateServiceImpl(override val jobTemplateRepository: JobTemplateRepository, jobTemplateResolutionUtil: JobTemplateResolutionService) extends JobTemplateService {
```
Comment (kevinwallimann) [inline src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateService.scala]: rename the variable to service as well

Comment (jozefbakus) [reply src/main/scala/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateService.scala]: Fixed

**Review by kevinwallimann — APPROVED** [review]
