### PR TITLE
Feature/492 fix notification rules

### LINKED ISSUE #492: Fix notification rules query if there are no rules
A test like this fails:
  
```
  it should "not die" in {
    val result = await(notificationRuleRepository.getMatchingNotificationRules(1L, Failed, LocalDateTime.now()))
  }
```
with the error message
```
empty.head
java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:193)
	at za.co.absa.hyperdrive.trigger.persistance.NotificationRuleRepositoryImpl$$anonfun$getMatchingNotificationRules$8.apply(NotificationRuleRepository.scala:127)
```

because there are no (matching) notification rules

### PR DESCRIPTION
**Pull request by DKTRZHR000**
closes #492

### CODE REVIEW

File: src/test/scala/za/co/absa/hyperdrive/trigger/api/rest/services/NotificationRuleServiceTest.scala [hunk 1]
```diff
@@ -168,13 +168,13 @@ class NotificationRuleServiceTest extends AsyncFlatSpec with Matchers with Mocki
...
     when(notificationRuleRepository.getMatchingNotificationRules(eqTo(42L), eqTo(DagInstanceStatuses.Failed),
-      any[LocalDateTime]())(any[ExecutionContext])).thenReturn(Future{matchingRules})
+      any[LocalDateTime]())(any[ExecutionContext])).thenReturn(Future{Some(matchingRules)})
 
     // when
     val result = await(underTest.getMatchingNotificationRules(42L, DagInstanceStatuses.Failed))
 
     // then
-    result shouldBe matchingRules
+    result.value shouldBe matchingRules
```
Comment (kevinwallimann) [inline src/test/scala/za/co/absa/hyperdrive/trigger/api/rest/services/NotificationRuleServiceTest.scala:177]: Nice! Didn't know about `OptionValues`

**Review by kevinwallimann — APPROVED** [review]

File: src/test/scala/za/co/absa/hyperdrive/trigger/api/rest/services/NotificationRuleServiceTest.scala (hunk 1 above)
Comment (DKTRZHR000) [reply src/test/scala/za/co/absa/hyperdrive/trigger/api/rest/services/NotificationRuleServiceTest.scala:177]: Agreed, makes things easier. Btw there are Either values as well, also very useful https://www.scalatest.org/user_guide/using_EitherValues
